<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="canonical" href="https://qmacro.org/blog/posts/2020/07/21/continue-on-error-can-prevent-a-job-step-failure-causing-an-action-failure/"><link href="/assets/main.b6be6784e8575ba25795.css" rel="stylesheet"><link rel="preconnect" href="https://fonts.gstatic.com"><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans&display=swap" rel="stylesheet"><title>continue-on-error can prevent a job step failure causing an action failure | DJ Adams</title><link rel="icon" type="“image/x-icon”" href="/images/favicon.ico"><meta property="og:title" content="continue-on-error can prevent a job step failure causing an action failure"><meta property="og:site_name" content="DJ Adams"><meta property="og:type" content="website"><meta property="og:url" content="https://qmacro.org/blog/posts/2020/07/21/continue-on-error-can-prevent-a-job-step-failure-causing-an-action-failure/"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:creator" content="@qmacro"><meta name="description" content="continue-on-error can prevent a job step failure causing an action failure 21 Jul 2020 | 1 min read Use continue-on-error: true in a GitHub..."><meta property="og:description" content="continue-on-error can prevent a job step failure causing an action failure 21 Jul 2020 | 1 min read Use continue-on-error: true in a GitHub..."><meta name="description" content="continue-on-error can prevent a job step failure causing an action failure 21 Jul 2020 | 1 min read Use continue-on-error: true in a GitHub..."><meta property="og:image" content="https://qmacro.org/images/site-image.png"><meta name="twitter:image" content="https://qmacro.org/images/site-image.png"><script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script><script>mermaid.initialize({startOnLoad:true});</script><script async src="https://www.googletagmanager.com/gtag/js?id=G-4WQKBG0L4Y"></script><script>window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-4WQKBG0L4Y');</script></head><body><div class="layout-wrapper"><header class="header"><div class="header__content"><h1 class="site-title"><a href="/">DJ Adams</a></h1><nav class="nav"><ul class="nav__list"><li class="nav-item"><a href="/about">About Me</a></li><li class="nav-item"><a href="/talks">Talks</a></li><li class="nav-item"><a href="/blog">Blog</a></li><li class="nav-item"><a href="/feed.xml">Feed</a></li></ul></nav></div></header><main class="main"><article class="post"><header class="post__header"><h1>continue-on-error can prevent a job step failure causing an action failure</h1><div class="post__details"><time datetime="2020-07-21">21 Jul 2020 </time><span>| </span><span>1 min read</span></div></header><main class="post__content"><p><em>Use <code>continue-on-error: true</code> in a GitHub Actions job spec to prevent failures from being flagged when a job step fails.</em></p><p>For me, high (non-zero) return codes don't always necessarily denote failure; sometimes I want to use a high return code to control step execution (see <a href="https://qmacro.org/2020/07/20/github-actions-step-conditional/">TIL: git diff can emit different exit codes</a>). But this means that the entire workflow run is marked as failed in a GitHub Action context. To prevent this, you can use <a href="https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error"><code>continue-on-error</code></a> at the job level to prevent a workflow from failing when a job fails.</p><p>I <a href="https://github.com/qmacro/qmacro/commit/42217c8a53108856dfcc85108f2cca4731bfa1ba">added this</a> to my build workflow and it works nicely. See for example <a href="https://github.com/qmacro/qmacro/actions/runs/178511479">action execution 178511479</a> - i.e. even when there was a step that ended with a high return code (deliberately, to signify no changes), the entire execution was still marked as a success:</p><p><img src="/images/2020/07/successfulaction.png" alt="action marked as success"></p><p>(Hat tip to <a href="https://github.com/jung-thomas">Tom Jung</a> for this).</p></main><aside class="post__aside"><div class="post__tags"><a href="/tags/autodidactics/">#autodidactics</a> <a href="/tags/github-actions/">#github-actions</a></div><style>.utterances {
  margin-left: inherit !important;
}</style><script src="https://utteranc.es/client.js" repo="qmacro/qmacro.github.io" issue-term="title" crossorigin="anonymous" async></script><nav class="post__pagination"><a href="/blog/posts/2020/08/04/string.prototype.replace()-can-take-a-function/"><span>←</span> <span>String.prototype.replace() can take a function</span> </a><a href="/blog/posts/2020/07/20/git-diff-can-emit-different-exit-codes/"><span>git diff can emit different exit codes</span> <span>→</span></a></nav></aside></article></main><footer class="footer"><div class="footer__content"><ul class="hero__social-links"><li><a rel="me" href="https://github.com/qmacro" target="_blank" rel="noopener noreferrer">GitHub</a></li><li><a rel="me" href="https://www.youtube.com/djadams-qmacro" target="_blank" rel="noopener noreferrer">YouTube</a></li><li><a rel="me" href="https://twitter.com/qmacro" target="_blank" rel="noopener noreferrer">Twitter</a></li><li><a rel="me" href="https://hachyderm.io/@qmacro" target="_blank" rel="noopener noreferrer">Mastodon</a></li><li><a href="/feed.xml" target="_blank" rel="noopener noreferrer">RSS</a></li></ul></div></footer></div><script src="/assets/main.31d6cfe0d16ae931b73c.js"></script></body></html>